import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'
import { Container } from '@chakra-ui/react'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Ingles e Tal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
        
        <Script type="text/javascript" src="https://d335luupugsy2.cloudfront.net/js/rdstation-forms/stable/rdstation-forms.min.js" />
      </body>
    </html>
  )
}
